#!/bin/sh

status()
{  run_timelapse=$(cat /run/timelapse1s.status)
   if [ "$run_timelapse" == true ]; then
   echo "started"
   fi
}

running()
{
  run_timelapse=$(cat /run/timelapse1s.status)
  while $run_timelapse; do
	run_timelapse=$(cat /run/timelapse1s.status)
	/system/sdcard/bin/getimage > /system/sdcard/DCIM/`date +%d-%m-%Y_%H.%M.%S`.jpg &
	# /system/sdcard/bin/getimage > /system/sdcard/DCIM/`date +%d-%m-%Y_%H.%M.%S`.jpg  &>/dev/null ##change me
	echo "created img " `date +%d-%m-%Y_%H.%M.%S`.jpg
	sleep 1s
  done
}


start()
{
  LOG=/dev/null
  echo "Starting timelapse"
  echo true > /run/timelapse1s.status
  running &
  PID=$!
  echo $PID
}

stop()
{
  echo false > /run/timelapse1s.status
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi